version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  catalog-db:
    container_name: c209-catalog-db
    build:
      dockerfile: Dockerfile
      context: ./database
    image: 1w2k/catalog-db
    environment:
      - MARIADB_DATABASE=test
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "7777:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)